name: Convert Video to TikTok Format

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'URL of the MP4 video'
        required: true
        type: string

jobs:
  convert-video:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download video from URL
        run: |
          mkdir -p video_input
          wget -O video_input/input.mp4 "${{ github.event.inputs.video_url }}"
          chmod 644 video_input/input.mp4
          ls -l video_input/

      - name: Convert video using autoflip with development config
        run: |
          docker run --rm -v ${{ github.workspace }}/video_input:/video \
            -e input_video=input.mp4 \
            -e output_video=tiktok_version.mp4 \
            -e aspect_ratio=9:16 \
            -e config=development \
            -e frames_output=debug_frames.mp4 \
            -e points_output=debug_points.mp4 \
            lathi/autoflip:latest

      - name: Upload all debug videos
        uses: actions/upload-artifact@v4
        with:
          name: debug-videos
          path: |
            video_input/tiktok_version.mp4
            video_input/debug_frames.mp4
            video_input/debug_points.mp4
