name: Convert Video to TikTok Format

on:
  workflow_dispatch:  # Only manual trigger

jobs:
  convert-video:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find MP4 file and set permissions
        id: find-mp4
        run: |
          VIDEO_FILE=$(ls *.mp4 | head -n 1)
          echo "video_file=$VIDEO_FILE" >> $GITHUB_OUTPUT
          chmod 644 "$VIDEO_FILE"

      - name: Create video directory
        run: |
          mkdir -p video_input
          cp ${{ steps.find-mp4.outputs.video_file }} video_input/
          chmod -R 755 video_input

      - name: Convert video using autoflip with development config
        run: |
          docker run --rm -v ${{ github.workspace }}/video_input:/video \
            -e input_video=${{ steps.find-mp4.outputs.video_file }} \
            -e output_video=tiktok_version.mp4 \
            -e aspect_ratio=9:16 \
            -e config=development \
            -e frames_output=debug_frames.mp4 \
            -e points_output=debug_points.mp4 \
            daniloleemes/autoflip

      - name: Upload all debug videos
        uses: actions/upload-artifact@v4
        with:
          name: debug-videos
          path: |
            video_input/tiktok_version.mp4
            video_input/debug_frames.mp4
            video_input/debug_points.mp4
