name: Convert Video to TikTok Format

on:
  push:
    paths:
      - '*.mp4'  # Trigger when MP4 files are pushed
  workflow_dispatch:  # Allow manual trigger

jobs:
  convert-video:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find MP4 file
        id: find-mp4
        run: |
          VIDEO_FILE=$(ls *.mp4 | head -n 1)
          echo "video_file=$VIDEO_FILE" >> $GITHUB_OUTPUT

      - name: Convert video using autoflip
        run: |
          docker run -v ${{ github.workspace }}:/video \
            -e input_video=${{ steps.find-mp4.outputs.video_file }} \
            -e output_video=tiktok_version.mp4 \
            -e aspect_ratio=9:16 \
            lathi/autoflip:latest

      - name: Upload converted video
        uses: actions/upload-artifact@v2
        with:
          name: tiktok-video
          path: tiktok_version.mp4

      - name: Commit and push converted video
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add tiktok_version.mp4
          git commit -m "Add converted TikTok video"
          git push
